name: deploy

run-name: Commit by ${{ github.actor }}

on:
  push:
    branches:
      - deploy-test





jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v