name: deploy 

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: excuting remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
    - name: pass enviroment
      uses: appleboy/ssh-action@master
      env:
        FOO: bar
        DB_DB: ${{ secrets.DB_DB }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: FOO, DB_DB