name: CI

on:
  push:
    branches: deploy
  pull_request:
    branches: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12,14,16 ]

    steps:
      - name: checkout to repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - run: npm test