name: Deploy to NCP Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t your-username/your-app .
          docker push your-username/your-app

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - name: Set up NCP Container Registry
        uses: ncloud/ncloud-cli-action@v1
        with:
          ncloud_access_key_id: ${{ secrets.NCP_ACCESS_KEY }}
          ncloud_secret_access_key: ${{ secrets.NCP_SECRET_KEY }}

      - name: Login to NCP Container Registry
        run: |
          ncloud cli login

      - name: Push Docker image to NCP Container Registry
        run: |
          ncloud cli container registry push your-username/your-app